import {login, logout, getUser, handleAuthCallback, acceptInvite, requestPasswordRecovery, updateUser} from '@netlify/identity'
import YAML from 'yaml'

const root = document.getElementById('app')
const demo = ['localhost', '127.0.0.1'].includes(location.hostname)
const state = {user: null, mode: 'readonly', view: 'home', path: null, sha: null, data: null, postBody: '', message: '', error: '', reviewed: null}
const field = (key, label, max = 160, type = 'text', options) => ({key, label, max, type, options})
const pageHome = [field('hero_line','Main headline',24),field('hero_accent','Highlighted word',16),field('hero_lead','Short introduction',130,'textarea'),field('timetable_intro','Timetable introduction',130,'textarea'),field('welcome_one','Welcome paragraph one',230,'textarea'),field('welcome_two','Welcome paragraph two',230,'textarea'),field('principles_intro','Principles introduction',140,'textarea'),field('principle_welcoming','Welcoming card',130,'textarea'),field('principle_dedicated','Dedicated card',130,'textarea'),field('principle_passion','Passion card',130,'textarea'),field('principle_integrity','Integrity card',130,'textarea'),field('ways_intro','Ways to practise introduction',150,'textarea')]
const pageClasses = [field('timetable_intro','Timetable introduction',130,'textarea'),field('categories_intro','Class categories introduction',150,'textarea'),field('reviews_intro','Reviews introduction',150,'textarea'),field('heat_one','About infrared heat',330,'textarea'),field('heat_two','Unheated classes',170,'textarea'),field('heat_three','What to bring to a hot class',340,'textarea'),field('pregnancy_one','Pregnancy yoga introduction',220,'textarea'),field('pregnancy_two','Pregnancy yoga details',260,'textarea'),field('pregnancy_three','Pregnancy yoga closing',200,'textarea')]
const pageMembership = [field('hero_intro','Pricing introduction',160,'textarea'),field('newcomer_intro','Newcomer introduction',170,'textarea'),field('benefits_intro','Benefits introduction',130,'textarea'),field('benefit_mood','Find your mood',150,'textarea'),field('benefit_temperature','Your temperature',150,'textarea'),field('benefit_welcome','A warm welcome',160,'textarea'),field('benefit_community','Community',170,'textarea'),field('benefit_teachers','Teachers',140,'textarea'),field('benefit_home','Practise at home',160,'textarea'),field('help_intro','Help choosing',170,'textarea')]
const cardFields = [field('id','Internal card ID',40),field('size','Card size',0,'select',['big','standard']),field('kind','Card type',0,'select',['event','news','class','post','offer']),field('tag','Small label',24),field('headline','Front headline',44),field('sub','Front detail',70),field('body','Back description',230,'textarea'),field('cta','Button wording',36),field('href','Button link',220),field('image','Photo',220,'image','images'),field('colour','Card colour',0,'select',['mint','purple','coral','yellow']),field('expires','Last day to show',0,'date')]
const classFields = [field('time','Start time',0,'time'),field('name','Class name',32),field('style','Colour group',0,'select',['flow','sweat','calm','found'])]
const planFields = [field('id','Plan ID',40),field('label','Name',45),field('product_id','Momence product ID',30),field('amount','Website price in £',0,'number'),field('momence_confirmed_amount','Confirmed Momence price in £',0,'number'),field('booking_url','Momence checkout link',240)]
const generalFields = [field('eyebrow','Small label',45),field('headline','Main headline',55),field('intro','Introduction',270,'textarea'),field('hero_image','Hero photo',220,'image','images/retreats'),field('hero_alt','Photo description',130),field('story_heading','Experience heading',65),field('story','Experience description',320,'textarea'),field('past_heading','Past retreats heading',65),field('past_place','Past retreat location',65),field('past_description','Past retreat description',280,'textarea'),field('quote','Guest review',280,'textarea'),field('interest_heading','Interest form heading',65),field('interest_description','Interest form introduction',240,'textarea')]
const retreatFields = [field('title','Retreat name',58),field('published','Make this the featured retreat',0,'checkbox'),field('sold_out','Sold out or bookings closed',0,'checkbox'),field('go_live','First day to show',0,'date'),field('end_date','Last retreat day',0,'date'),field('hide_after','Hide earlier on this date',0,'date'),field('eyebrow','Small hero label',35),field('subtitle','Short introduction',180,'textarea'),field('location','Location',65),field('date_label','Dates shown to visitors',55),field('price_label','Price wording',50),field('hero_image','Hero photo',220,'image','images/retreats'),field('hero_alt','Photo description',130),field('overview_heading','Experience heading',70),field('overview','Retreat story',500,'textarea'),field('booking_url','Booking link',240),field('booking_cta','Booking button wording',36)]
const postFields = [field('title','Article headline',100),field('description','Article summary and default search description',220,'textarea'),field('seo_title','Search result title (optional)',65),field('seo_description','Search result description (optional)',160,'textarea'),field('category','Category',0,'select',['Beginners','Breathwork','Hot yoga','Poses','Wellbeing','Yoga 101']),field('published','Publication date',0,'date'),field('readTime','Reading time',30),field('image','Cover image',220,'image','images/blog'),field('hero_alt','Cover image alt text (optional)',130),field('social_image','Social sharing image (optional)',220,'image','images/blog')]
const sections = [
  {id:'home-copy',title:'Homepage wording',intro:'Change the words visitors see on the homepage. Character limits protect the layout.',path:'content/page-copy/home.json',fields:pageHome},
  {id:'classes-copy',title:'Classes wording',intro:'Edit classes-page descriptions. The weekly schedule has its own section.',path:'content/page-copy/classes.json',fields:pageClasses},
  {id:'membership-copy',title:'Membership wording',intro:'Edit membership descriptions. Prices have their own safety check.',path:'content/page-copy/membership.json',fields:pageMembership},
  {id:'latest',title:'Latest cards',intro:'Refresh the five homepage cards. Set an end date for time-limited promotions.',path:'content/latest.json',list:'tiles',itemFields:cardFields},
  {id:'timetable',title:'Weekly timetable',intro:'Update the website timetable here. Bookings in Momence must be changed separately.',path:'content/timetable.json',list:'days',fixed:true},
  {id:'prices',title:'Membership prices',intro:'First update each matching product in Momence, then confirm the same amount here.',path:'content/prices.json',list:'plans',itemFields:planFields,fixed:true},
  {id:'retreats-general',title:'General retreats page',intro:'This appears whenever there is no active retreat on sale.',path:'content/retreats-general.json',fields:generalFields},
  {id:'retreats',title:'Upcoming retreats',intro:'Create and manage a dated retreat landing page.',collection:'retreats'},
  {id:'posts',title:'Blog posts',intro:'Write a new post or update one of the existing articles.',collection:'posts'},
  {id:'media',title:'Media library',intro:'Browse site photos and videos, see file details, and check how each one is described on the website.'},
  {id:'health',title:'Site health',intro:'See what is working, what needs attention, and when hands-on checks were last completed.'},
]

function el(tag, className, text) { const node=document.createElement(tag); if(className) node.className=className; if(text!==undefined) node.textContent=text; return node }
function button(text, className, onClick) {const node=el('button',className,text);node.type='button';node.addEventListener('click',onClick);return node}
function message(text, error=false) {return el('div',`message${error?' message--error':''}`,text)}
function escapeHtml(value) {return String(value).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;')}
function setMessage(text,error=false){state.message=error?'':text;state.error=error?text:'';const slot=document.getElementById('status');if(slot)slot.replaceChildren(text?message(text,error):'')}
function slug(value) {return String(value).normalize('NFKD').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,80)}

function loginScreen(mode='login',token=''){
  root.innerHTML=`<div class="login"><section class="login__brand"><div class="login__logo"><img src="/images/logo.png" alt="Vanessa Flow Yoga logo"><span>VANESSA<br>FLOW YOGA</span></div><div class="login__welcome"><span class="login__kicker">A little space to grow</span><h1>Your studio,<br>your stories.</h1><p>Keep the words, classes, stories and retreats on your website feeling just like you.</p></div><a href="https://vanessaflowyoga.co.uk">← Back to the website</a></section><section class="login__form-wrap"><div class="login__card"><span class="eyebrow">Vanessa Flow Yoga · website studio</span><h2>${mode==='invite'?'Set your password':mode==='recovery'?'Choose a new password':mode==='forgot'?'Reset your password':'Lovely to see you'}</h2><p class="muted">${mode==='login'?'Sign in to look after your website.':'This account is for the website admin only.'}</p><div id="status"></div><form id="auth-form">${mode==='login'||mode==='forgot'?'<label class="field"><span>Email address</span><input name="email" type="email" autocomplete="email" required></label>':''}${mode!=='forgot'?`<label class="field"><span>${mode==='login'?'Password':'New password'}</span><input name="password" type="password" autocomplete="${mode==='login'?'current-password':'new-password'}" minlength="12" required></label>`:''}<button class="btn btn--primary full" type="submit">${mode==='invite'?'Create account':mode==='recovery'?'Save new password':mode==='forgot'?'Send reset link':'Sign in'}</button></form><p><button id="auth-switch" class="btn btn--plain" type="button">${mode==='login'?'Forgot your password?':'Back to sign in'}</button></p></div></section></div>`
  document.getElementById('auth-switch').onclick=()=>loginScreen(mode==='login'?'forgot':'login')
  if(demo)document.getElementById('status').replaceChildren(message('Visual preview only. Email/password sign-in becomes active after Netlify Identity is enabled.'))
  document.getElementById('auth-form').onsubmit=async(event)=>{
    event.preventDefault();const form=event.currentTarget;const submit=form.querySelector('button[type=submit]');submit.disabled=true;setMessage('')
    try{const data=new FormData(form);if(mode==='login') await login(data.get('email'),data.get('password'))
      else if(mode==='forgot'){await requestPasswordRecovery(data.get('email'));setMessage('Check your inbox for a password reset link.');return}
      else if(mode==='invite') await acceptInvite(token,data.get('password'))
      else await updateUser({password:data.get('password')})
      state.user=await getUser();await loadMode();renderShell();openHome()
    }catch(error){setMessage(error.message||'Unable to sign in. Please try again.',true)}finally{submit.disabled=false}
  }
}

function renderShell(){
  root.innerHTML=`<div class="shell"><aside class="sidebar" id="sidebar"><div class="sidebar__brand"><img src="/images/logo.png" alt="Vanessa Flow Yoga logo"><span>VANESSA<br>FLOW YOGA<small>Website studio</small></span><button class="mobile-menu" id="menu-button" aria-label="Open menu">☰</button></div><nav id="side-nav"></nav><div class="sidebar__bottom"><div>${escapeHtml(state.user?.email||'Local preview')}</div><button id="sign-out">Sign out</button></div></aside><div class="main"><header class="topbar"><strong>Website studio <span>✳</span></strong><a href="https://vanessaflowyoga.co.uk" target="_blank" rel="noopener">View live website ↗</a></header><main class="content" id="content"></main></div></div>`
  const nav=document.getElementById('side-nav');nav.appendChild(button('Overview','',openHome));for(const section of sections)nav.appendChild(button(section.title,'',()=>openSection(section.id)))
  document.getElementById('menu-button').onclick=()=>document.getElementById('sidebar').classList.toggle('open')
  document.getElementById('sign-out').onclick=async()=>{if(!demo)await logout();state.user=null;loginScreen()}
}
function activeNav(label){document.querySelectorAll('#side-nav button').forEach(b=>b.classList.toggle('active',b.textContent===label));document.getElementById('sidebar').classList.remove('open')}
function openHome(){state.view='home';activeNav('Overview');const content=document.getElementById('content');content.innerHTML='<section class="hero"><span class="eyebrow">Your website studio</span><h1>Welcome back to the flow.</h1><p>Choose an area to update. Check your changes in Preview before you publish them to the website.</p></section><div class="quick-grid" id="quick-grid"></div><div class="note"><strong>Site health</strong><br><span id="health-status">Checking monitoring…</span><br><span id="credential-status">Checking content connection…</span><br><button type="button" id="health-open">Open health checks →</button></div><div class="note"><strong>Good to know</strong><br>Website timetable and prices do not change Momence bookings or checkout products. Check those separately before publishing here.</div>';const grid=document.getElementById('quick-grid');for(const section of sections){const card=button('', 'quick',()=>openSection(section.id));card.innerHTML=`<strong>${escapeHtml(section.title)}</strong><span>${escapeHtml(section.intro)}</span><em>Open section →</em>`;grid.appendChild(card)}document.getElementById('health-open').onclick=()=>openSection('health');loadHealth()}
async function loadHealth(){const slot=document.getElementById('health-status');const credentialSlot=document.getElementById('credential-status');if(demo){slot.textContent='Open Site health to preview the dashboard. Live checks appear after sign-in.';credentialSlot.textContent='GitHub connection status appears here after sign-in.';return}try{const response=await fetch('/.netlify/functions/admin-health',{credentials:'same-origin'});const data=await response.json();if(!response.ok)throw Error(data.error||'Monitoring unavailable');slot.textContent=data.status==='not-run'?'No site health check has run yet.':data.status==='stale'?'Checks are overdue. Open Site health to run them now.':data.status==='attention'?`${data.report.summary.fail} checks need attention.`:data.status==='warning'?`${data.report.summary.warn} checks need review.`:'Last site health check passed.';const credential=data.credential;const date=new Date(`${credential.expiresAt}T00:00:00Z`).toLocaleDateString('en-GB',{day:'numeric',month:'long',year:'numeric'});credentialSlot.textContent=credential.status==='missing'?'GitHub content connection is not set up yet.':credential.status==='expired'?`Action needed: GitHub content token expired on ${date}.`:credential.status==='expiring'?`Action needed: GitHub content token expires on ${date} (${credential.daysLeft} days left).`:`GitHub content token expires on ${date}.`;credentialSlot.classList.toggle('message--error',credential.status==='missing'||credential.status==='expired'||credential.status==='expiring')}catch{slot.textContent='Monitoring status unavailable.';credentialSlot.textContent='GitHub connection status unavailable.'}}
function heading(title,intro){const wrap=el('div','page-head');const left=el('div');left.innerHTML=`<span class="eyebrow">Manage content</span><h1>${escapeHtml(title)}</h1><p>${escapeHtml(intro)}</p>`;wrap.appendChild(left);return wrap}
async function api(query,options){if(demo){if(options)throw Error('Local preview is read-only. Sign in on the hosted admin to save.');const url=new URLSearchParams(query);if(url.has('collection')){const posts=url.get('collection')==='posts';const r=await fetch(posts?'/content/latest-posts.json':'/content/retreat-list.json');if(!r.ok)throw Error('Could not load preview entries.');const data=await r.json();return {entries:posts?data.posts.map(p=>({name:p.title,path:`post/${p.href.split('/').pop()}.md`})):(data.retreats||[]).map(r=>({name:r.title,path:`content/retreats/${r.slug}.json`}))}}if(url.get('path')?.endsWith('.md'))throw Error('Existing blog articles open after the hosted admin is connected.');const r=await fetch('/'+url.get('path'));if(!r.ok)throw Error('Could not load local preview data.');return {path:url.get('path'),sha:null,content:await r.text()}}const url='/.netlify/functions/admin-content?'+new URLSearchParams(query);const r=await fetch(url,{credentials:'same-origin',...options});const json=await r.json();if(!r.ok)throw Error(json.error||'Unable to load content.');return json}
async function loadMode(){try{state.mode=(await api({mode:'1'})).mode}catch{state.mode='readonly'}}
async function openSection(id){const section=sections.find(s=>s.id===id);state.view=id;activeNav(section.title);const content=document.getElementById('content');content.replaceChildren(heading(section.title,section.intro),el('div','loading','Loading…'));try{if(id==='media'){await openMedia(section);return}if(id==='health'){await openHealth(section);return}if(section.collection){await listEntries(section);return}const entry=await api({path:section.path});state.path=section.path;state.sha=entry.sha;state.data=JSON.parse(entry.content);renderEditor(section)}catch(error){content.appendChild(message(error.message,true))}}

function formatBytes(bytes){return bytes<1024?`${bytes} B`:bytes<1048576?`${Math.round(bytes/1024)} KB`:`${(bytes/1048576).toFixed(1)} MB`}
function mediaCard(asset){
  const card=el('details','media-card');const summary=el('summary','media-card__summary');const thumb=el('span','media-card__thumb');let dimensions=null
  if(asset.type==='image'){const image=el('img');image.src=asset.path;image.alt='';image.loading='lazy';image.onload=()=>{if(dimensions)dimensions.textContent=`${image.naturalWidth} × ${image.naturalHeight} px`};thumb.appendChild(image)}
  else thumb.appendChild(el('span','media-card__video','▶ Video'))
  const identity=el('span','media-card__identity');identity.append(el('strong','',asset.filename),el('small','',`${asset.format} · ${formatBytes(asset.bytes)} · ${asset.uses.length} ${asset.uses.length===1?'reference':'references'}`));summary.append(thumb,identity,el('span','media-card__chevron','⌄'));card.appendChild(summary)
  const body=el('div','media-card__body');dimensions=el('p','media-card__dimensions',asset.type==='video'?'Video file':'Dimensions load with the image');body.appendChild(dimensions)
  const original=el('a','media-card__original','Open original ↗');original.href=asset.path;original.target='_blank';original.rel='noopener';body.appendChild(original)
  const imageUses=asset.uses.filter(use=>use.kind==='Image'||use.kind==='Background image');const altValues=[...new Set(imageUses.map(use=>use.alt).filter(value=>value!==null))]
  body.appendChild(el('h3','','Alt text on the site'))
  if(!imageUses.length)body.appendChild(el('p','muted','No image placement with alt text was found.'))
  else if(!altValues.length)body.appendChild(el('p','media-warning','No alt text found in the indexed page placements.'))
  else for(const alt of altValues)body.appendChild(el('p','media-alt',alt===''?'Empty alt text (decorative image)':alt))
  const titles=[...new Set(asset.uses.map(use=>use.title).filter(Boolean))]
  body.appendChild(el('h3','','Image title'))
  body.appendChild(el('p','muted',titles.length?titles.join(' · '):'No separate image title is set. Page and article titles are listed below.'))
  body.appendChild(el('h3','','Used on'))
  if(!asset.uses.length)body.appendChild(el('p','muted','No reference found in the current site build. It may be unused or loaded dynamically.'))
  else {
    const list=el('ul','media-uses');for(const use of asset.uses){const item=el('li');const label=use.pageTitle||use.page;const link=el('a','',label);link.href=use.page;link.target='_blank';link.rel='noopener';item.appendChild(link);item.appendChild(el('small','',`${use.kind}${use.alt===null?'':use.alt===''?' · decorative':` · alt: ${use.alt}`}`));list.appendChild(item)}body.appendChild(list)
  }
  card.appendChild(body);return card
}
async function openMedia(section){
  const content=document.getElementById('content');const response=await fetch('/admin/media-library.json',{cache:'no-store'});if(!response.ok)throw Error('Could not load the media library.');const data=await response.json();
  content.replaceChildren(heading(section.title,section.intro));const note=el('div','note','This library reads the current site build. Alt text belongs to each page placement, so one photo may have several descriptions. This view does not edit files or page wording.');content.appendChild(note)
  const controls=el('div','media-controls');const search=el('input');search.type='search';search.placeholder='Search filename, page or alt text';search.setAttribute('aria-label','Search media');const filter=el('select');filter.setAttribute('aria-label','Filter media');for(const [value,label] of [['all','All media'],['images','Images'],['videos','Videos'],['unreferenced','No references found'],['missing-alt','Missing alt text']]){const option=el('option','',label);option.value=value;filter.appendChild(option)}controls.append(search,filter);content.appendChild(controls)
  const count=el('p','media-count');const grid=el('div','media-grid');content.append(count,grid)
  function render(){const term=search.value.trim().toLowerCase();const matches=data.assets.filter(asset=>{if(filter.value==='images'&&asset.type!=='image')return false;if(filter.value==='videos'&&asset.type!=='video')return false;if(filter.value==='unreferenced'&&asset.uses.length)return false;if(filter.value==='missing-alt'&&!asset.uses.some(use=>use.kind==='Image'&&use.alt===null))return false;return !term||[asset.path,...asset.uses.flatMap(use=>[use.pageTitle,use.page,use.alt,use.title])].some(value=>String(value||'').toLowerCase().includes(term))});count.textContent=`${matches.length} of ${data.assets.length} files`;grid.replaceChildren(...matches.map(mediaCard));if(!matches.length)grid.appendChild(el('p','muted','No media matches this search.'))}
  search.addEventListener('input',render);filter.addEventListener('change',render);render()
}

const healthLabels={availability:'Site and admin',pages:'All pages',links:'Internal and external links',security:'Security and HTTPS',seo:'Search and blog SEO',forms:'Forms configured',media:'Images and videos',speed:'Page response speed',integrations:'Instagram and Momence',github:'GitHub connection'}
async function healthApi(suffix='',options){const response=await fetch('/.netlify/functions/admin-health'+suffix,{credentials:'same-origin',...options});const data=await response.json();if(!response.ok)throw Error(data.error||'Health checks are unavailable.');return data}
function healthStatusLabel(status){return status==='fail'?'Needs attention':status==='warn'?'Check manually':status==='pass'?'Working':'Not checked'}
async function openHealth(section){
  const content=document.getElementById('content');const data=demo?{status:'not-run',report:null,categories:Object.keys(healthLabels),manualItems:[{id:'form:contact',label:'contact form delivery',url:'/contact'},{id:'form:membership',label:'membership form delivery',url:'/membership'},{id:'form:application',label:'application form delivery',url:'/work-with-us'},{id:'form:retreat-interest',label:'retreat-interest form delivery',url:'/retreats'},{id:'cookies',label:'Cookie consent and GDPR review',url:'/cookies'},{id:'speed',label:'Real-world page speed review',url:'/'},{id:'mobile',label:'Mobile layout review',url:'/'}],settings:{recipients:['hello@charlie-harris.com','vanessa@vanessaflowyoga.co.uk'],alertCategories:Object.keys(healthLabels),manual:{}},alertsConfigured:false,credential:{status:'ok',expiresAt:'2026-10-24'}}:await healthApi()
  content.replaceChildren(heading(section.title,section.intro))
  const toolbar=el('div','health-toolbar');const run=button('Run checks now','btn btn--primary',async()=>{run.disabled=true;run.textContent='Checking the website…';feedback.textContent='Checking pages, links, images and services. This can take a moment.';try{await healthApi('?run=1',{method:'POST',headers:{'content-type':'application/json'},body:'{}'});await openHealth(section)}catch(error){feedback.textContent=error.message;run.disabled=false;run.textContent='Run checks now'}});run.disabled=demo;toolbar.appendChild(run);const checked=data.report?.checkedAt?new Date(data.report.checkedAt).toLocaleString('en-GB'):'Never';toolbar.appendChild(el('span','muted',`Last automatic check: ${checked}`));content.appendChild(toolbar)
  const feedback=el('div','health-feedback');feedback.setAttribute('role','status');content.appendChild(feedback)
  const overview=el('div',`health-overview health-overview--${data.status}`);overview.appendChild(el('strong','',data.status==='attention'?`${data.report.summary.fail} checks need attention`:data.status==='warning'?`${data.report.summary.warn} checks need review`:data.status==='healthy'?'Automatic checks passed':data.status==='stale'?'Checks are overdue':'No automatic results yet'));overview.appendChild(el('p','',data.status==='not-run'?'The daily monitor will run after deployment. You can also run it here.':'Automatic checks do not submit forms or prove legal compliance. Hands-on test records are below.'));content.appendChild(overview)
  const categories=el('div','health-categories');for(const category of data.categories){const rows=data.report?.results.filter(item=>item.category===category)||[];const fail=rows.filter(item=>item.status==='fail').length,warn=rows.filter(item=>item.status==='warn').length;const status=!rows.length?'unknown':fail?'fail':warn?'warn':'pass';const card=el('details',`health-category health-category--${status}`);const summary=el('summary');summary.append(el('span','health-dot',status==='pass'?'✓':status==='fail'?'!':status==='warn'?'?':'–'),el('strong','',healthLabels[category]||category),el('small','',!rows.length?'Not checked yet':fail?`${fail} failed`:warn?`${warn} need review`:`${rows.length} passed`));card.appendChild(summary);const list=el('div','health-results');for(const item of rows){const row=el('div',`health-result health-result--${item.status}`);row.appendChild(el('span','',healthStatusLabel(item.status)));const main=el('div');main.appendChild(el('strong','',item.name));if(item.detail)main.appendChild(el('small','',item.detail));if(item.url){const link=el('a','','Open ↗');link.href=item.url;link.target='_blank';link.rel='noopener';main.appendChild(link)}row.appendChild(main);list.appendChild(row)}if(!rows.length)list.appendChild(el('p','muted','No result has been recorded yet.'));card.appendChild(list);categories.appendChild(card)}content.appendChild(categories)
  const manual=el('section','panel health-manual');manual.appendChild(el('h2','','Hands-on checks'));manual.appendChild(el('p','muted','A page loading is not proof that a form reaches an inbox, cookies are compliant, or mobile pages look right. Record these only after you have checked them.'))
  for(const item of data.manualItems){const record=data.settings.manual?.[item.id];const row=el('div','manual-row');const left=el('div');left.appendChild(el('strong','',item.label));left.appendChild(el('small','',record?`${record.status==='pass'?'✓ Passed':'! Failed'} · last tested ${new Date(record.checkedAt).toLocaleString('en-GB')}`:'Not tested yet'));row.appendChild(left);const actions=el('div','manual-actions');const open=el('a','btn btn--soft',item.id.startsWith('form:')?'Open form ↗':'Open page ↗');open.href='https://vanessaflowyoga.co.uk'+item.url;open.target='_blank';open.rel='noopener';actions.appendChild(open);for(const [status,label] of [['pass',item.id.startsWith('form:')?'I confirmed receipt':'I checked — passed'],['fail','Mark failed']]){const control=button(label,status==='pass'?'btn btn--soft':'btn btn--plain',async()=>{if(demo)return;control.disabled=true;try{await healthApi('?manual='+encodeURIComponent(item.id),{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({status})});await openHealth(section)}catch(error){feedback.textContent=error.message;control.disabled=false}});control.disabled=demo;actions.appendChild(control)}row.appendChild(actions);manual.appendChild(row)}content.appendChild(manual)
  const alerts=el('section','panel health-alerts');alerts.appendChild(el('h2','','Email me if…'));alerts.appendChild(el('p','muted','Choose who receives an email when a selected check is red. Addresses are stored privately with the admin project. Alerts run daily.'))
  if(!data.alertsConfigured)alerts.appendChild(el('div','message message--error','Email sending is not active yet. Add RESEND_API_KEY and HEALTH_ALERT_FROM to this admin Netlify project, then redeploy and test delivery.'))
  const label=el('label','field');label.appendChild(el('span','','Notification email addresses (one per line)'));const emails=el('textarea');emails.value=data.settings.recipients.join('\n');emails.rows=3;label.appendChild(emails);alerts.appendChild(label)
  const choices=el('div','alert-choices');for(const category of [...new Set([...data.categories,'cookies','mobile'])]){const option=el('label','alert-choice');const input=el('input');input.type='checkbox';input.value=category;input.checked=data.settings.alertCategories.includes(category);option.append(input,el('span','',healthLabels[category]||{cookies:'Cookie/GDPR review',mobile:'Mobile review'}[category]));choices.appendChild(option)}alerts.appendChild(choices)
  const save=button('Save email choices','btn btn--primary',async()=>{if(demo)return;save.disabled=true;try{const recipients=emails.value.split(/[\n,;]+/).map(value=>value.trim()).filter(Boolean);const alertCategories=[...choices.querySelectorAll('input:checked')].map(input=>input.value);await healthApi('',{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify({recipients,alertCategories})});await openHealth(section)}catch(error){feedback.textContent=error.message;save.disabled=false}});save.disabled=demo;alerts.appendChild(save);content.appendChild(alerts)
  const expiry=new Date(`${data.credential.expiresAt}T00:00:00Z`).toLocaleDateString('en-GB');content.appendChild(el('div','note',`GitHub publishing token: ${data.credential.status==='expired'?'expired':data.credential.status==='expiring'?'renew soon':'expires'} ${expiry}.`))
}

function scalar(container,obj,spec){const label=el('label','field');label.appendChild(el('span','',spec.label));let input
  if(spec.type==='textarea')input=el('textarea');else if(spec.type==='select'){input=el('select');for(const option of spec.options){const choice=el('option','',option);choice.value=option;input.appendChild(choice)}}else{input=el('input');input.type=spec.type==='checkbox'?'checkbox':spec.type==='number'?'number':spec.type==='date'?'date':spec.type==='time'?'time':'text'}
  if(spec.max)input.maxLength=spec.max;if(spec.type==='checkbox'){input.checked=!!obj[spec.key];input.onchange=()=>obj[spec.key]=input.checked}else{input.value=obj[spec.key]??'';input.oninput=()=>{obj[spec.key]=spec.type==='number'?Number(input.value):input.value;if(spec.max)counter.textContent=`${input.value.length}/${spec.max}`}}
  label.appendChild(input);const counter=spec.max?el('small','count',`${String(obj[spec.key]??'').length}/${spec.max}`):null;if(counter)label.appendChild(counter);container.appendChild(label)
  if(spec.type==='image'){const upload=el('input');upload.type='file';upload.accept='image/jpeg,image/png,image/webp';upload.disabled=demo;const hint=el('small','',demo?'Photo upload is available after sign-in.':'Upload a JPG, PNG or WebP under 2 MB.');label.append(upload,hint);upload.onchange=async()=>{const file=upload.files?.[0];if(!file)return;try{if(file.size>2000000)throw Error('Choose a photo under 2 MB.');hint.textContent='Uploading photo…';const base64=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result).split(',')[1]);reader.onerror=()=>reject(Error('Could not read photo.'));reader.readAsDataURL(file)});const name=`${Date.now()}-${slug(file.name.replace(/\.[^.]+$/,''))}.${file.name.split('.').pop().toLowerCase()}`;const saved=await api({upload:'1'},{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({folder:spec.options,filename:name,base64})});obj[spec.key]=saved.path;input.value=saved.path;hint.textContent='Photo uploaded. Save this page to use it.'}catch(error){hint.textContent=error.message;upload.value=''}}}
}
function fields(container,obj,schema){const grid=el('div','form-grid');for(const spec of schema){const wrapper=el('div',spec.type==='textarea'?'wide':'');scalar(wrapper,obj,spec);grid.appendChild(wrapper)}container.appendChild(grid)}
function listEditor(container,items,schema,options={}){const holder=el('div');function redraw(){holder.replaceChildren();items.forEach((item,index)=>{const panel=el('div','subpanel');const head=el('div','subpanel__head');head.appendChild(el('h3','',options.title?options.title(item,index):`Item ${index+1}`));if(!options.fixed)head.appendChild(button('Remove','',()=>{items.splice(index,1);redraw()}));panel.appendChild(head);if(typeof item==='string'){const label=el('label','field');label.appendChild(el('span','','Description'));const input=el('input');input.maxLength=90;input.value=item;input.oninput=()=>items[index]=input.value;label.appendChild(input);panel.appendChild(label)}else fields(panel,item,schema);if(options.child){const sub=el('div');sub.appendChild(el('h3','','Classes'));listEditor(sub,item.classes,classFields,{title:(entry)=>`${entry.time||'New time'} · ${entry.name||'New class'}`,empty:()=>({time:'09:00',name:'',style:'flow'})});panel.appendChild(sub)}holder.appendChild(panel)});if(!options.fixed)holder.appendChild(button('+ Add another','btn btn--soft',()=>{items.push(options.empty());redraw()}))}redraw();container.appendChild(holder)}
function renderEditor(section,post=false){state.reviewed=null;const content=document.getElementById('content');content.replaceChildren(heading(section.title,section.intro));const panel=el('section','panel');panel.appendChild(el('h2','',post?'Article details':section.title));if(post){panel.appendChild(el('p','muted','Search fields are optional. Existing posts keep their current headline and summary until you add separate search wording. The article web address stays the same.'));fields(panel,state.data,postFields);const body=el('label','field');body.appendChild(el('span','','Article text'));const textarea=el('textarea','markdown');textarea.value=state.postBody;textarea.oninput=()=>state.postBody=textarea.value;body.appendChild(textarea);body.appendChild(el('small','','Use ## for section headings.'));panel.appendChild(body)}else if(section.fields)fields(panel,state.data,section.fields);else if(section.id==='latest')listEditor(panel,state.data.tiles,cardFields,{fixed:true,title:(item,index)=>`Card ${index+1} · ${item.headline||'Untitled'}`});else if(section.id==='timetable')listEditor(panel,state.data.days,[],{fixed:true,title:item=>item.day,child:true});else if(section.id==='prices')listEditor(panel,state.data.plans,planFields,{fixed:true,title:item=>item.label});else if(section.id==='retreat-entry'){fields(panel,state.data,retreatFields);for(const key of ['experiences','inclusions']){panel.appendChild(el('h2','',key==='experiences'?'What guests will do':'What is included'));listEditor(panel,state.data[key],[],{title:(item,index)=>String(item||`Item ${index+1}`),empty:()=>''})}}content.appendChild(panel)
  if(section.id==='prices')content.appendChild(el('div','note','Before saving: update the matching Momence products. The website build will reject a price that does not match the confirmed Momence amount.'))
  const actions=el('div','editor-actions');actions.appendChild(el('small','',state.mode==='live'?'Preview your changes before publishing to the live site.':state.mode==='review'?'Preview your changes before saving to the review branch. The live website will not change.':'Preview only · saving is not enabled yet.'));const group=el('div','action-buttons');group.appendChild(button('Preview','btn btn--soft',()=>previewEntry(section,post)));const save=button(state.mode==='live'?'Publish changes':'Save to review','btn btn--primary',()=>saveEntry(section,post));save.disabled=state.mode==='readonly';group.appendChild(save);actions.appendChild(group);content.appendChild(actions);const status=el('div');status.id='status';content.appendChild(status)
}
function currentDraft(){return JSON.stringify({data:state.data,body:state.postBody})}
function previewEntry(section,post){
  state.reviewed=currentDraft();document.querySelector('.preview-modal')?.remove();
  const modal=el('div','preview-modal');const dialog=el('div','preview-dialog');modal.appendChild(dialog);
  const bar=el('div','preview-bar');bar.appendChild(el('strong','','Preview · '+section.title));bar.appendChild(button('Close preview ×','btn btn--plain',()=>modal.remove()));dialog.appendChild(bar);
  const page={ 'home-copy':'/index.html', 'classes-copy':'/classes.html', 'membership-copy':'/membership.html', 'retreats-general':'/retreats.html' }[section.id];
  if(page){const frame=el('iframe','preview-frame');frame.title='Website page preview';frame.src=page;frame.onload=()=>{try{const doc=frame.contentDocument;for(const [key,value] of Object.entries(state.data)){const node=doc.querySelector(`[data-copy="${key}"], [data-retreat-copy="${key}"], [data-copy-key="${key}"]`);if(node)node.textContent=key==='quote'?`“${value}”`:value}if(section.id==='retreats-general'){const photo=doc.querySelector('[data-retreat-image]');if(photo){photo.src=state.data.hero_image;photo.alt=state.data.hero_alt}}}catch{}};dialog.appendChild(frame)}
  else {const sheet=el('div','preview-sheet');sheet.appendChild(el('span','eyebrow','Vanessa Flow Yoga · content preview'));sheet.appendChild(el('h1','',post?state.data.title:section.title));if(post){sheet.appendChild(el('p','',state.data.description));const article=el('div','preview-article');for(const paragraph of state.postBody.split(/\n\s*\n/)){if(paragraph.trim())article.appendChild(el(paragraph.startsWith('## ')?'h2':'p','',paragraph.replace(/^## /,'')))}sheet.appendChild(article)}else if(section.id==='latest'){const grid=el('div','preview-cards');for(const card of state.data.tiles){const tile=el('div','preview-card');tile.style.backgroundImage=`linear-gradient(transparent,#241b38bd),url('${card.image}')`;tile.append(el('small','',card.tag),el('h2','',card.headline),el('p','',card.sub));grid.appendChild(tile)}sheet.appendChild(grid)}else if(section.id==='timetable'){for(const day of state.data.days){const row=el('div','preview-row');row.appendChild(el('strong','',day.day));row.appendChild(el('span','',day.classes.map(c=>`${c.time} ${c.name}`).join(' · ')||'No classes'));sheet.appendChild(row)}}else if(section.id==='prices'){for(const plan of state.data.plans){const row=el('div','preview-row');row.appendChild(el('strong','',plan.label));row.appendChild(el('span','',`£${plan.amount}`));sheet.appendChild(row)}}else{for(const spec of retreatFields){const value=state.data[spec.key];if(typeof value==='string'&&value)sheet.appendChild(el(spec.key==='title'?'h2':'p','',value))}}dialog.appendChild(sheet)}
  const foot=el('div','preview-foot');foot.appendChild(el('span','',page?'Preview of this page with your wording changes.':'Content preview; final page layout is generated when published.'));foot.appendChild(button('Back to editing','btn btn--primary',()=>modal.remove()));dialog.appendChild(foot);document.body.appendChild(modal)
}
async function saveEntry(section,post){try{if(state.reviewed!==currentDraft())throw Error('Please preview your latest changes before publishing.');if(section.id==='prices'&&state.data.plans.some(p=>p.amount!==p.momence_confirmed_amount))throw Error('Each website price must match the price you confirmed in Momence.');if(section.id==='latest'&&state.data.tiles.filter(t=>t.size==='big').length!==1)throw Error('Exactly one latest card must be the big card.');if(section.id==='timetable'&&state.data.days.some(d=>d.classes.some((c,i)=>i&&c.time<d.classes[i-1].time)))throw Error('Keep classes in time order within each day.');if(section.id==='retreat-entry'&&state.data.go_live>state.data.end_date)throw Error('The last retreat day must be after its first day.');const path=state.path||`${post?'post':'content/retreats'}/${slug(state.data.title)}.${post?'md':'json'}`;if(!path||path.endsWith('/.md')||path.endsWith('/.json'))throw Error('Enter a title before publishing.');const text=post?`---\n${YAML.stringify(state.data)}---\n\n${state.postBody.trim()}\n`:JSON.stringify(state.data,null,2)+'\n';const result=await api({path},{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify({path,sha:state.sha,content:text})});state.path=path;state.sha=result.sha;state.reviewed=null;setMessage(result.message||'Published.')}catch(error){setMessage(error.message,true)}}
async function listEntries(section){const content=document.getElementById('content');content.replaceChildren(heading(section.title,section.intro));const add=button(section.id==='posts'?'+ New blog post':'+ New retreat','btn btn--primary',()=>newEntry(section));content.querySelector('.page-head').appendChild(add);const list=el('div','entry-list');content.appendChild(list);const result=await api({collection:section.collection});for(const entry of result.entries){const name=entry.name.replace(/\.(md|json)$/,'').replaceAll('-',' ');list.appendChild(button(`${name}  →`,'entry',()=>openEntry(section,entry.path)))}if(!result.entries.length)list.appendChild(el('p','muted','No entries yet.'))}
function newEntry(section){state.path=null;state.sha=null;if(section.id==='posts'){state.data={title:'',description:'',category:'Wellbeing',published:new Date().toISOString().slice(0,10),readTime:'3 min read'};state.postBody='';renderEditor({id:'post-entry',title:'New blog post',intro:'Write your article, then save it to add it to the site.'},true)}else{state.data={schema_version:'1.0',title:'',published:false,sold_out:false,go_live:'',end_date:'',hide_after:'',eyebrow:'Your next retreat',subtitle:'',location:'',date_label:'',price_label:'',hero_image:'',hero_alt:'',overview_heading:'',overview:'',experiences:[],inclusions:[],booking_url:'',booking_cta:'Explore this retreat'};renderEditor({id:'retreat-entry',title:'New retreat',intro:'Add the story, dates and booking details. Turn on featured when ready.'})}}
async function openEntry(section,path){const content=document.getElementById('content');content.replaceChildren(heading(section.title,section.intro),el('div','loading','Loading entry…'));try{const entry=await api({path});state.path=path;state.sha=entry.sha;if(section.id==='posts'){const match=/^---\r?\n([\s\S]*?)\r?\n---\r?\n([\s\S]*)$/.exec(entry.content);if(!match)throw Error('Could not read the article details.');state.data=YAML.parse(match[1]);state.postBody=match[2];renderEditor({id:'post-entry',title:state.data.title,intro:'Edit this article. The web address stays the same.'},true)}else{state.data=JSON.parse(entry.content);renderEditor({id:'retreat-entry',title:state.data.title,intro:'Edit this retreat page and its showing dates.'})}}catch(error){content.appendChild(message(error.message,true))}}

async function boot(){if(demo){if(new URLSearchParams(location.search).has('login-preview')){loginScreen();return}state.user={email:'Local preview'};renderShell();openHome();return}try{const callback=await handleAuthCallback();if(callback?.type==='invite'){loginScreen('invite',callback.token);return}if(callback?.type==='recovery'){loginScreen('recovery');return}state.user=await getUser();if(state.user){await loadMode();renderShell();openHome()}else loginScreen()}catch(error){loginScreen();setMessage(error.message||'The admin login is not available yet.',true)}}
boot()
